# -*- coding: utf-8 -*-
"""bls_jobs_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vJe0PbAtoFnONc6A8VJnQKT9Cd0woAIz
"""

import requests
import pandas as pd
import plotly.express as px
import streamlit as st
from datetime import datetime

# Define the API key
API_KEY = "44b5edc711ba40c8885a6d169dfefbf8"

# Clear Streamlit's cache
st.cache_data.clear()
st.cache_resource.clear()

# Function to calculate percentage changes
def calculate_percentage_change(df, comparison_type):
    df = df.copy() # Avoid modifying the original dataframe
    if comparison_type == "MoM":
        df["change"] = df["value"].pct_change() * 100
        title = "Employment Percent Change by Month"
    elif comparison_type == "YoY":
        df["change"] = df["value"].pct_change() * 100
        title = "Employment Percent Change by Year"
    return df, title

# Function to fetch data using the BLS API
def fetch_data(series_id):
    url = "https://api.bls.gov/publicAPI/v2/timeseries/data/"
    headers = {"Content-Type": "application/json"}
    payload = {
        "seriesid": [series_id],
        "startyear": "2014",
        "endyear": str(datetime.now().year),
        "registrationkey": API_KEY,
    }

    response = requests.post(url, json=payload, headers=headers)
    if response.status_code == 200:
        json_data = response.json()
        series_data = json_data.get("Results", {}).get("series", [])
        if series_data:
            data_points = series_data[0].get("data", [])
            data = [
                {
                    "date": f"{dp['periodName']} {dp['year']}",
                    "value": float(dp["value"]),
                }
                for dp in data_points
            ]
            df = pd.DataFrame(data)
            df["date"] = pd.to_datetime(df["date"], format="%B %Y")
            df = df.sort_values(by="date")
            return df
    else:
        st.error(f"Error fetching data: {response.status_code} - {response.text}")
        return pd.DataFrame()

# Streamlit app
st.title("BLS Employment and Unemployment Data Dashboard")

# Fetch employment and unemployment data
with st.spinner("Fetching employment data..."):
    employment_df = fetch_data("CES0000000001")  # Non-farm employment
    if not employment_df.empty:
        st.success("Employment data fetched successfully!")
    else:
        st.error("Failed to fetch employment data.")

with st.spinner("Fetching unemployment data..."):
    unemployment_df = fetch_data("LNS14000000")  # Unemployment rate
    if not unemployment_df.empty:
        st.success("Unemployment data fetched successfully!")
    else:
        st.error("Failed to fetch unemployment data.")

# Check if data exists
if not employment_df.empty and not unemployment_df.empty:
    unemployment_df["type"] = "Unemployment Rate"
    employment_df["type"] = "Employment Level"
    combined_df = pd.concat([employment_df, unemployment_df])

    # Display the combined dataframe
    st.subheader("BLS Employment and Unemployment Data")
    st.dataframe(combined_df)

    # Create slicer for visualization
    data_type = st.selectbox(
        "Select Data Type:",
        ["Employment Level", "Unemployment Rate", "Employment Percentage Change by Month", "Employment Percentage Change by Year"]
    )

    if data_type == "Employment Level" or data_type == "Unemployment Rate":
        # Filter data based on the selection
        filtered_df = combined_df[combined_df["type"] == data_type]

        fig = px.line(
            filtered_df,
            x="date",
            y="value",
            title=data_type,
            labels={"date": "Date", "value": data_type},
            template="simple_white"
        )
    else:
        # Apply percentage change to employment data only
        comparison_type = "MoM" if "Month" in data_type else "YoY"
        employment_df, title = calculate_percentage_change(employment_df, comparison_type)

        fig = px.line(
            employment_df,
            x="date",
            y="change",
            title=title,
            labels={"date": "Date", "change": "% Change"},
            template="simple_white"
        )

    st.plotly_chart(fig)
else:
    st.info("No data available to display.")
