# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B37XqhVdgvTtwacf1ct03b5qVEawaPdv
"""

# prepare_data.py
import pandas as pd

# Define the file path to the BLS data file
DATA_FILE = "bls_data.csv"
Total_NF_Employment = "https://download.bls.gov/pub/time.series/ce/ce.data.00a.TotalNonfarm.Employment"

# Load and clean the data
def prepare_data():
    df = pd.read_csv("https://www.bls.gov/news.release/empsit.htm")

    # Convert 'date' column to datetime format if not already done
    df["date"] = pd.to_datetime(df["date"], errors="coerce")

    # Sort by date
    df = df.sort_values("date").reset_index(drop=True)

    # Handle missing values
    df.fillna(method="ffill", inplace=True)  # Forward fill missing values

    # Pivot data for easy dashboard usage
    pivoted_df = df.pivot_table(
        index="date", columns="series_id", values="value"
    ).reset_index()

    pivoted_df.columns.name = None  # Remove the name of the columns index
    pivoted_df.to_csv("prepared_data.csv", index=False)
    print("Data successfully prepared and saved.")

if __name__ == "__main__":
    prepare_data()

# dashboard.py
import streamlit as st

# Load the prepared data
DATA_FILE = "prepared_data.csv"

def load_data():
    return pd.read_csv(DATA_FILE, parse_dates=["date"])

# Create the dashboard
def main():
    st.title("US Labor Statistics Dashboard")
    df = load_data()

    # Sidebar filters
    st.sidebar.header("Filter Options")
    selected_series = st.sidebar.multiselect(
        "Select Metrics", df.columns[1:], default=df.columns[1:]
    )

    # Filter data
    filtered_df = df[["date"] + selected_series]

    # Plot the data
    st.line_chart(filtered_df.set_index("date"))

    # Display raw data option
    if st.checkbox("Show raw data"):
        st.write(filtered_df)

if __name__ == "__main__":
    main()